#pragma once
namespace Coda {
	namespace Frontend {
		enum class NodeType {

			// Statements
			INVALID,
			PROGRAM,
			ARGUMENT_LIST,

			VARIABLE_DECLARATION,
			CONSTANT_DECLARATION,

			// Expressions
				//Literals
			BYTE_LITERAL,
			INTEGER_LITERAL,
			LONG_INT_LITERAL,
			FLOATING_POINT_LITERAL,
			DOUBLE_LITERAL,
			CHARACTER_LITERAL,
			STRING_LITERAL,
			PROPERTY,
			OBJECT_LITERAL,

				//Other
			IDENTIFIER,
			BINARY_EXPRESSION,
			ASSIGNMENT_EXPRESSION,
			MEMBER_EXPRESSION,
			CALL_EXPRESSION

		};

	}
}